### ISSUE TITLE
Add support for new pageview endpoints

### ISSUE THREAD

**Issue by geohci** [mediawiki-utilities/python-mwviews#16]
In particular, I think based on https://wikimedia.org/api/rest_v1/#/Pageviews%20data, we'd need to add `top-by-country` (monthly top countries for readers of a project) and `top-per-country` (daily most viewed articles for a given country). I don't know when I could get to this but I'm happy to take it on if someone doesn't beat me to it.

**Comment by milimetric** [comment]
I'm happy to review, ping me if you don't have time and I'll try to find some.  You're right the new endpoints should be in here, I had totally forgotten about this library, my bad.

**Comment by geohci** [comment]
Thanks @milimetric ! PR #17 added which hopefully addresses this. I tested locally and was working but I easily could have missed something. I also updated the README with examples.
