### ISSUE TITLE
Querying a page title with a questionmark

### ISSUE THREAD

**Issue by edoderoo** [mediawiki-utilities/python-mwviews#2]
When I query daily statistics on a page containing a questionmark, like  p.article_views(u'nl.wikipedia',['Wie is de mol?'],start=startday,end=endday) it will result in zeroes as number of page views.

**Comment by milimetric** [comment]
Thanks for letting me know, fixed in the last push (pip install mwviews --upgrade will get version 0.0.6 where your query works).
