### ISSUE TITLE
Is there a way to search by QID?

### ISSUE THREAD

**Issue by DeanStra** [mediawiki-utilities/python-mwviews#21]
I have a csv with a list of Wiki QIDs, but frustrating no more direct information about their wikipedia pages. Does mwviews have a setting to search by QID?

Thank you!

**Comment by milimetric** [comment]
No QID search yet, as that information is not stored centrally.  We'd have to create a new dataset that correlates QID with articles (and that's not a 1/1 mapping so we'd probably have to talk about semantic relationships).  That's beyond the scope of mwviews.  You might want to try to see if other people are interested in this, the analytics mailing list used to be a place to have such conversations: https://lists.wikimedia.org/postorius/lists/analytics.lists.wikimedia.org/
