### ISSUE TITLE
Enforce high-volume access acceptable usage patterns

### ISSUE THREAD

**Issue by AGFeldman** [mediawiki-utilities/python-mwviews#5]
The [API documentation](https://wikimedia.org/api/rest_v1/?doc) requests/requires that high-volume users:

- Don't perform more than 500 requests/s to this API
- Set a unique `User-Agent` header that allows us to contact you quickly. Email addresses or URLs of contact pages work well.

I would like to not worry about following this policy when I use this tool.

**Comment by milimetric** [comment]
We are in the process of setting up throttling that will throw an HTTP 429 error when you exceed the configured number of requests.  I'll close this in favor of the issue on phabricator: https://phabricator.wikimedia.org/T135240

**Comment by milimetric** [comment]
This is done, you can issue requests as always and not worry about this).   We'll throw the right error code if needed
